### ISSUE TITLE
Actualizar el apartado 1: Introducción y Objetivos.

### ISSUE THREAD

**Issue by PablooD9** [Arquisoft/inci_e2a#1]

**Comment by Jose-agg** [comment]
Dejo aqui el enlace del word sobre el que trabajaremos para hacer la documentacion:
https://unioviedo-my.sharepoint.com/:w:/g/personal/uo251317_uniovi_es/ETHUdS_GyjNHiUy6GJEVLPoB6QVrTnqh-6XOqBtsLwIL5w?e=cE5Ztd

**Comment by Jose-agg** [comment]
Primer punto completado
