### ISSUE TITLE
Revisión de la documentación para la primera entrega:

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#11]
- [ ] Cesar.
- [ ] Fernando.
- [x] Jesús.
- [x] Pablo.
- [x] Pelayo.
- [x] Peyjo.
- [x] Jose.

**Comment by Jose-agg** [comment]
He sido el encargado principal de hacer el documento he ido revisando cada punto. No he encontrado mas errores salvo los mencionados en cada issue.

**Comment by PablooD9** [comment]
Se tiene que actualizar la parte Loader del punto 9 (vistas). Pablo Álvarez y yo estamos con ello.

**Comment by Pelayo-Torre** [comment]
He actualizado, junto con Jesús García Minas, la parte de Agents del punto 9 (Vistas) de la documentación.

**Comment by PablooD9** [comment]
Doy por revisado el punto 9 (Vistas) de la parte Loader.

**Comment by Jose-agg** [comment]
Ya se hizo la primera entrega, por lo que cierro esta issue
