### ISSUE TITLE
Arreglar la imagen del punto 9.2.1. En concreto, los "arcos" de las relaciones.

### ISSUE THREAD

**Issue by PablooD9** [Arquisoft/inci_e2a#12]

**Comment by PablooD9** [comment]
Visual Paradigm está dando problemas con la estructura de las relaciones...

**Comment by pabloalvrz** [comment]
Me la asigno yo, que esto ya es algo personal.

**Comment by pabloalvrz** [comment]
Finalizado el arreglo del diagrama.
