### ISSUE TITLE
Actualizar el punto 4: Identificación de Stakeholders. Segunda Entrega.

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#15]
Añadir nuevos stakeholders si se ve necesario, puede que ya estén incluidos todos.

**Comment by Pelayo-Torre** [comment]
Añadido StakeHolder -> Operarios que resuelven incidencias.

**Comment by cesarcamblor** [comment]
Jesús García Minas y yo modificamos el stakeholder añadido de Operarios juntándolo con Entidades colaboradoras ya que realizaban acciones similares.
