### ISSUE TITLE
Actualizar el punto 5: Atributos de calidad. Segunda Entrega.

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#16]
Es necesario crear nuevos atributos de calidad en función de los nuevos requisitos que tendrá el sistema.
Este punto tiene bastante trabajo.

**Comment by Pelayo-Torre** [comment]
Jesús García Minas, César Camblor García y yo Pelayo García Torre, hemos actualizado el punto 5 de la documentación referido a los atributos de calidad.
