### ISSUE TITLE
Actualizar el punto 7: Ámbito del sistema y contexto. Segunda Entrega.

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#17]
Es necesario agregar los 2 nuevos módulos a este punto.

**Comment by Jose-agg** [comment]
Para este punto yo ya he hecho el diagrama de contexto de negocio. Si creéis que es necesario modificarlo, decírmelo que yo puedo modificar este para que concuerde con lo que se decida.
![version2](https://user-images.githubusercontent.com/35923796/36449640-aa256b3e-168b-11e8-8609-929a32e8425f.PNG)

**Comment by ferpobe** [comment]
Punto actualizado en local a falta de revisión por parte del equipo antes de actualizarlo.

**Comment by ferpobe** [comment]
Revisar para poner tipo de estilo dashboard

**Comment by PablooD9** [comment]
Actualizado (y revisado) el punto 7. Falta actualizar el diagrama BPMN.
