### ISSUE TITLE
Actualizar el punto 8: Escenarios de calidad. Segunda Entrega.

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#18]
Es necesario añadir nuevos escenarios de calidad para TODOS los atributos de calidad que se hayan agregado al punto 5 de la documentación.

**Comment by ferpobe** [comment]
Nuevo escenarios para revisar.
![aaaaabbbb](https://user-images.githubusercontent.com/23242435/36911267-502b3748-1e43-11e8-833f-827dec5ba7a1.PNG)

**Comment by pabloalvrz** [comment]
Está bien, no obstante yo cambiaría algunas cosas en la redacción para que quedaran más claras.

**Comment by pabloalvrz** [comment]
Modifiqué el escenario nº17 ya que creo que tu lo enfocaste como el 16, y el atributo de calidad tenía que ver con rendimiento y no con seguridad. Tambien falta por revisar/hacer el 21 que no se ve completamente en la imagen. El atributo de calidad del escenario 19 no es el 18 ya que este habla de la interaccióon con un cha-bot, lo modifiqué y le puse el 19 que habla de la visualización gráfica de las incidencias. Échale un vistazo a las modificaciones y me dices @ferpobe

**Comment by cesarcamblor** [comment]
He revisado las modificaciones de @PabloAlvarezUO251561 y el punto 8 en general  y me parecen correctas. He correjido errores de ortografía y he cambiado algunas cosas (pocas) para que esten un poco más claras. Queda poner la medición de la respuesta del escenario 17 que yo tampoco se que poner. Revisa tu tambien si puedes @ferpobe a ver que te parece todo

**Comment by pabloalvrz** [comment]
Acabo de añadir el escenario de calidad relativo al atributo de calidad 18(chat-bot)

**Comment by pabloalvrz** [comment]
Revisar los 24/7. Para el atributo 15, a parte de tener un escenario para el que no se cumple. Necesitamos añadir un nuevo atributo de calidad, " El sistema debe permitir el acceso a agentes que no se encuentren registrados", esto conlleva a tener que crear un escenario nuevo .
