### ISSUE TITLE
Actualizar el punto 9: Vistas (grupo Agents). Segunda Entrega.

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#19]
Hay que revisar los diagramas del primer modulo, y hacer la documentación para el nuevo modulo: InciDashboard.

**Comment by Jose-agg** [comment]
Estoy haciendo el punto 9.5.2: Catalogo de elementos y sus subpuntos

**Comment by Pelayo-Torre** [comment]
Voy a realizar el punto 9.3.1 en Visual Paradigm.

**Comment by Pelayo-Torre** [comment]
Ya está subido el nuevo diagrama.

**Comment by Pelayo-Torre** [comment]
Corregida la nueva documentación del punto 9 (Agents) con los nuevos campos.

**Comment by Jose-agg** [comment]
Punto 9.5.2: Catalogo de elementos de la vista de Incidence Dashboard completado.
Quedan por hacer el diagrama de Presentacion principal, punto 9.5.1., y la Justificacion de las decisiones, punto 9.5.4.

**Comment by JesusGarciaMinas** [comment]
Realizado el punto 9.5.4 con los escenarios de calidad que corresponden a este módulo

**Comment by Pelayo-Torre** [comment]
He realizado el diagrama correspondiente a la presentación principal del módulo InciDashBoard (Punto 9.5.1).

**Comment by Jose-agg** [comment]
Como todos hemos acabado, cierro esta issue

**Comment by PablooD9** [comment]
Toca retocar las vistas y el nombre de los componentes para el módulo InciDashboard.
