### ISSUE TITLE
Actualizar el punto 9: Vistas (grupo Loader) . Segunda Entrega.

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#20]
Hay que revisar los diagramas del primer modulo, y hacer la documentación para el nuevo modulo: InciManager.

**Comment by PablooD9** [comment]
Hace falta, además, actualizar las relaciones que aparecen en el diagrama de Loader, en el que están los paquetes Parser, Business y ReportWriter ( issue #12 )

**Comment by PablooD9** [comment]
Añadida la parte InciManager en las vistas, así como la imagen de la vista asociada, relaciones entre elementos e interfaces/puertos.

**Comment by PablooD9** [comment]
Añadida la justificación de decisiones de los atributos de calidad. Falta el diagrama de contexto.

**Comment by PablooD9** [comment]
Toca retocar las vistas y el nombre de los componentes para el módulo InciManager.
