### ISSUE TITLE
Revisión de la documentación para la segunda entrega.

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#22]
- [ ] Cesar.
- [ ] Fernando.
- [x] Jesús.
- [x] Pablo.
- [ ] Pelayo.
- [ ] Peyjo.
- [x] Jose.

**Comment by Jose-agg** [comment]
He revisado la documentacion y corregido un error en stakeholders bastante importante y otros errores menores

**Comment by JesusGarciaMinas** [comment]
He revisado la documentación y he corregido el pie de página para adecuarlo al segundo entregable
