### ISSUE TITLE
Diagrama de contexto

### ISSUE THREAD

**Issue by cesarcamblor** [Arquisoft/inci_e2a#24]
Hay que hacer y actualizar los nombres del diagrama de contexto

**Comment by cesarcamblor** [comment]
Ya he modificado algún nombre que estaba mal en el diagrama.

**Comment by pabloalvrz** [comment]
Falta que el resto del equipo revise nuestro diagrama. Ir dejando comentarios. Cierro issue cuando todos esteis de acuerdo

**Comment by pabloalvrz** [comment]
Añadir al diagrama de contexto las vistas restantes: InciManager e InciDashboard.

**Comment by PablooD9** [comment]
Diagrama de contexto hecho, así como toda su vista.
