### ISSUE TITLE
Crear BBDD común

### ISSUE THREAD

**Issue by cesarcamblor** [Arquisoft/inci_e2a#28]
Hay que crear una base de datos online común.

**Comment by cesarcamblor** [comment]
Tras los problemas encontrados con los grupos de seguridad de AWS hemos decidido cambiar nuestro proveedor de base de datos a freemysqlhosting.net
La integración de esta BBDD con el dashboard ha sido satisfactoria.
Hay que comprobar que funcione bien en el Inci_Manager

**Comment by Jose-agg** [comment]
# Motivo #
La base de datos de freemysqlhosting.net nos limitaba la cantidad de conexiones al mismo tiempo que se podían hacer por lo que he decidido cambiar todas las bases de datos a AWS. Dejo aquí los pasos que he seguido por si fuera necesario replicarlo en el futuro. También añadiré los datos necesarios para hacer las conexiones pero me voy a encargar yo de que los 4 módulos tengan las conexiones correctamente actualizadas.

- - -

# Pasos #

Es necesario tener creada una cuenta en Amazon Web Service con un laboratorio para trabajar. Cuando este todo esto listo vas al apartado de servicios y escoges la opción **EC2** donde crearemos una instancia de una maquina virtual, en este caso una maquina Ubuntu.

![image](https://user-images.githubusercontent.com/35923796/39479378-6b0f81ee-4d65-11e8-8326-b5fdc301615e.png)

Luego seguiremos la guía de instalación dejando todo por defecto para así evitar que la maquina consuma dinero de la cuenta, hasta que lleguemos al apartado 6. Aquí se configurará el grupo de seguridad, que es básicamente abrir los puertos que vayamos a necesitar a todo el mundo y una conexión SSH para conectarnos a la propia maquina.

![image](https://user-images.githubusercontent.com/35923796/39479821-b039c12a-4d66-11e8-920e-c3f0d3b5b18f.png)


Una vez hecho esto lazamos la maquina y esperamos a que ésta aparezca en el panel de control en verde. Una vez nos aparezca en verde copiamos el EndPoint y la IPv4 que nos aparezca

![image](https://user-images.githubusercontent.com/35923796/39479751-76bbe2de-4d66-11e8-9fc1-d0d9fbc6ae1b.png)

Ahora, desde un cliente SSH, pones en el host el EndPoint, como usuario ubuntu, que es el usuario con privilegios por defecto que proporciona Amazon, y conectas la clave publica. Una vez hecho esto estableces la conexion con la maquina.

![image](https://user-images.githubusercontent.com/35923796/39479906-eaa1828a-4d66-11e8-87be-22f460343afa.png)

Dentro de la maquina se veria algo tal que así.

![image](https://user-images.githubusercontent.com/35923796/39480154-a61d0250-4d67-11e8-9681-1d6e58224e6c.png)

Una vez dentro se ejecutarían los siguientes comandos. Solo explicaré los comandos que crea que no son intuitivos.

```
sudo apt-get update
sudo apt-get install mysql-server     // Apuntar la contraseña root, por si acaso *1
mysql_secure_installation            // No es necesario, pero permite configurar unos parámetros de seguridad
systemctl status mysql.service         // Comprobar que el servicio esta activado
mysql --user=root --password=contraseña *1
```
```
// Ahora estaríamos dentro del servicio mysql
CREATE DATABASE `<<bbdd>>`;
show databases;    // Comprueba que se han creado todas las bases de datos
CREATE USER '<<usuario>>' IDENTIFIED BY '<<contraseña>>';

GRANT USAGE ON *.* TO '<<usuario>>'@'%' IDENTIFIED BY '<<contraseña>>';   // Concede permisos de acceso al usuario desde cualquier sitio: %
GRANT ALL privileges ON `<<bbdd>>`.* TO '<<usuario>>'@'%';
FLUSH PRIVILEGES;     // Aplicar los cambios

SHOW GRANTS FOR '<<usuario>>'@'%';      // Comprobar que los permisos son correctos
{Control+D}     // Para salir de mysql
```
```
 // Buscas la linea que ponga bind-address=AAA.BBB.CCC.DDD en el siguiente fichero y cambias la IP por 0.0.0.0. De esta forma se permite el acceso remoto
sudo nano /etc/mysql/mysql.conf.d/mysqld.cnf

// Ahora es necesario abrir el puerto 3306, por lo que añadiremos una excepción en el firewall
sudo iptables -A INPUT -i eth0 -p tcp --destination-port 3306 -j ACCEPT

// Reiniciamos el servicio para que se actualicen los cambios y ya estaría todo configurado
sudo /etc/init.d/mysql restart

```

- - -

# Datos #
Para evitar que estén tan al descubierto los datos de la maquina, el usuario, etc. adjuntaré los mismo en un mensaje a los desarrolladores y modificaré yo todos los módulos para que estén actualizados.

- - -

**Comment by Jose-agg** [comment]
Ya están todas las bases de datos modificadas, doy esta issue como terminada
