### ISSUE TITLE
Trabajo en grupo 26/04/2018

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#30]
Aqui comentaremos todo lo que haremos durante esta reunion grupal. Nos hemos dividido el trabajo para hacer avanzar el proyecto. La separacion de trabajo es la siguiente:
- Buscar el despliegue de una base de datos para pruebas y otra para produccion para que todos los modulos. Encargados > @cesarcamblor y @Pelayo-Torre
- Separar la logica de Agents del InciManager. Encargado > @JesusGarciaMinas
- Buscar la forma de actualizar la interfaz de InciDashboard de forma automatica. Encargado > @PablooD9
- Juntar los modulos Agents, InciManager e InciDashboard en un este repositorio. Encargados > @MrKarrter @PabloAlvarezUO251561 y @Ferpobe

**Comment by pabloalvrz** [comment]
Estas son las ordenes que yo seguí:
 -Clono el repositorio: con git clone url.
 -Me muevo al repositorio clonado.
 -En el repositorio añado los submodules con : git add submodule url
 -Commit + push.

**Comment by pabloalvrz** [comment]
Arreglada el problema de submodules vacios cuando clonamos el repositorio "padre", la orden para hacerlo seria:
- git clone --recurse-submodules url

**Comment by Jose-agg** [comment]
Cierro esta issue de la reunion
