### ISSUE TITLE
Despliegue de la aplicacion

### ISSUE THREAD

**Issue by Jose-agg** [Arquisoft/inci_e2a#32]
Es necesario que los 4 módulos de esta aplicación estén desplegados en un servidor. Para realizar esto buscaremos la forma de hacerlo, empezando con Docker para meter los módulos en contenedores y Amazon Web Service como proveedor del servidor.

**Comment by PablooD9** [comment]
Bases de datos de producción y test desplegadas.
Kafka desplegado.

**Comment by Jose-agg** [comment]
He utilizado Amazon Web Service para el despliegue de los modulos. Todas las maquinas estan listas para la fase de produccion
