### ISSUE TITLE
Qué falta por hacer

### ISSUE THREAD

**Issue by PablooD9** [Arquisoft/inci_e2a#34]
Queda:

- Diagrama BPMN (punto 7)
- Vista de paquetes
- Vista de despliegue
- Vista de contexto
- ¿Loader?

**Comment by Jose-agg** [comment]
Yo estoy con el BPMN de toda la aplicacion. Basicamente al equivalente de esto, pero para el estado actual del proyecto.
![antiguo](https://user-images.githubusercontent.com/35923796/39671865-a78a9a50-5120-11e8-934c-c563c329a02b.png)

**Comment by pabloalvrz** [comment]
@cesarcamblor y yo estamos en el punto 9 y 9.1, también estamos revisando el punto 8.

**Comment by PablooD9** [comment]
Punto 9. Dashboard, terminado.
Vista de contexto terminada.
