### ISSUE TITLE
Actualizar el apartado 4: Identificación de Stakeholders.

### ISSUE THREAD

**Issue by PablooD9** [Arquisoft/inci_e2a#4]

**Comment by Jose-agg** [comment]
Actualizados los stakeholders y sus descripciones. Finalizado

**Comment by pabloalvrz** [comment]
Creo que deberiamos de especificar mejor los alumnos que realizamos la práctica. Habiamos hablado de que fueran dos stakeholders: el propio grupo y el otro grupo del equipo. Reabre el issue si lo consideras.

**Comment by Jose-agg** [comment]
Eso lo habíamos hablado antes de que nos dijeran que se podía hacer una documentación conjunta. Piensa que este es el repositorio del proyecto final, por lo que solo hay un grupo de trabajo. Si quisiéramos dividirlo ¿quien seria "el propio grupo", el de Agents o el de Loader? ¿ Y "el otro grupo del equipo"?. 
¿Estas de acuerdo? @PabloAlvarezUO251561
